- name: Install Apache on a chosen host
  hosts: "{{ target_host | default('all') }}"
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Fix cho DNF issue 
  tasks:
    - name: Install Apache
      ansible.builtin.package:
        name: "{{ 'httpd' if ansible_facts.os_family == 'RedHat' else 'apache2' }}"
        state: present

    - name: Enable & start service
      ansible.builtin.service:
        name: "{{ 'httpd' if ansible_facts.os_family == 'RedHat' else 'apache2' }}"
        state: started
        enabled: true
