- name: Install Apache on a chosen host
  hosts: "{{ target_host | default('all') }}"
  become: true
  gather_facts: true
  tasks:
    - name: Update package cache (Debian/Ubuntu only)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: 
        - ansible_facts.os_family == "Debian"
        - ansible_facts.pkg_mgr == "apt"

    - name: Install Apache
      ansible.builtin.package:
        name: apache
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
