- name: Install Apache on a chosen host
  hosts: "{{ target_host | default('all') }}"
  become: true
  gather_facts: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: latest
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
