- name: Install Apache on a chosen host
  hosts: "{{ target_host | default('all') }}"
  become: true
  gather_facts: true
  tasks:
    - name: Install Apache
      ansible.builtin.command: dnf install -y httpd
      args:
        warn: no
    - copy:
        dest: /var/www/html/index.html
        content: "<h1>Hello from Ansible!</h1>"


