- name: Install Apache on a chosen host
  hosts: "{{ target_host | default('all') }}"
  become: true
  gather_facts: true
  tasks:
    - name: Install Apache
      ansible.builtin.command: dnf install -y httpd
      args:
        warn: no
    - name: Start Apache service
      service:
        name: apache2
        state: started
